/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedStudentManagementRouteImport } from './routes/_authenticated.student-management'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated.sos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSeatPlannerRouteImport } from './routes/_authenticated.seat-planner'
import { Route as AuthenticatedSchoolRulesRouteImport } from './routes/_authenticated.school-rules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedCorruptionMoneyRouteImport } from './routes/_authenticated.corruption-money'
import { Route as AuthenticatedClassFeedbackRouteImport } from './routes/_authenticated.class-feedback'
import { Route as AuthenticatedCaptainFeedbackListRouteImport } from './routes/_authenticated.captain-feedback-list'
import { Route as AuthenticatedCaptainFeedbackRouteImport } from './routes/_authenticated.captain-feedback'
import { Route as AuthenticatedAiSyllabusRouteImport } from './routes/_authenticated.ai-syllabus'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated.activity-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentManagementRoute =
  AuthenticatedStudentManagementRouteImport.update({
    id: '/student-management',
    path: '/student-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeatPlannerRoute =
  AuthenticatedSeatPlannerRouteImport.update({
    id: '/seat-planner',
    path: '/seat-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolRulesRoute =
  AuthenticatedSchoolRulesRouteImport.update({
    id: '/school-rules',
    path: '/school-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorruptionMoneyRoute =
  AuthenticatedCorruptionMoneyRouteImport.update({
    id: '/corruption-money',
    path: '/corruption-money',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassFeedbackRoute =
  AuthenticatedClassFeedbackRouteImport.update({
    id: '/class-feedback',
    path: '/class-feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaptainFeedbackListRoute =
  AuthenticatedCaptainFeedbackListRouteImport.update({
    id: '/captain-feedback-list',
    path: '/captain-feedback-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaptainFeedbackRoute =
  AuthenticatedCaptainFeedbackRouteImport.update({
    id: '/captain-feedback',
    path: '/captain-feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiSyllabusRoute = AuthenticatedAiSyllabusRouteImport.update({
  id: '/ai-syllabus',
  path: '/ai-syllabus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/ai-syllabus': typeof AuthenticatedAiSyllabusRoute
  '/captain-feedback': typeof AuthenticatedCaptainFeedbackRoute
  '/captain-feedback-list': typeof AuthenticatedCaptainFeedbackListRoute
  '/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/corruption-money': typeof AuthenticatedCorruptionMoneyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/student-management': typeof AuthenticatedStudentManagementRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/ai-syllabus': typeof AuthenticatedAiSyllabusRoute
  '/captain-feedback': typeof AuthenticatedCaptainFeedbackRoute
  '/captain-feedback-list': typeof AuthenticatedCaptainFeedbackListRoute
  '/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/corruption-money': typeof AuthenticatedCorruptionMoneyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/student-management': typeof AuthenticatedStudentManagementRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/ai-syllabus': typeof AuthenticatedAiSyllabusRoute
  '/_authenticated/captain-feedback': typeof AuthenticatedCaptainFeedbackRoute
  '/_authenticated/captain-feedback-list': typeof AuthenticatedCaptainFeedbackListRoute
  '/_authenticated/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/_authenticated/corruption-money': typeof AuthenticatedCorruptionMoneyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/_authenticated/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/student-management': typeof AuthenticatedStudentManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/activity-logs'
    | '/ai-syllabus'
    | '/captain-feedback'
    | '/captain-feedback-list'
    | '/class-feedback'
    | '/corruption-money'
    | '/notifications'
    | '/profile'
    | '/school-rules'
    | '/seat-planner'
    | '/settings'
    | '/sos'
    | '/student-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/activity-logs'
    | '/ai-syllabus'
    | '/captain-feedback'
    | '/captain-feedback-list'
    | '/class-feedback'
    | '/corruption-money'
    | '/notifications'
    | '/profile'
    | '/school-rules'
    | '/seat-planner'
    | '/settings'
    | '/sos'
    | '/student-management'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/landing'
    | '/login'
    | '/_authenticated/activity-logs'
    | '/_authenticated/ai-syllabus'
    | '/_authenticated/captain-feedback'
    | '/_authenticated/captain-feedback-list'
    | '/_authenticated/class-feedback'
    | '/_authenticated/corruption-money'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/school-rules'
    | '/_authenticated/seat-planner'
    | '/_authenticated/settings'
    | '/_authenticated/sos'
    | '/_authenticated/student-management'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-management': {
      id: '/_authenticated/student-management'
      path: '/student-management'
      fullPath: '/student-management'
      preLoaderRoute: typeof AuthenticatedStudentManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seat-planner': {
      id: '/_authenticated/seat-planner'
      path: '/seat-planner'
      fullPath: '/seat-planner'
      preLoaderRoute: typeof AuthenticatedSeatPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school-rules': {
      id: '/_authenticated/school-rules'
      path: '/school-rules'
      fullPath: '/school-rules'
      preLoaderRoute: typeof AuthenticatedSchoolRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corruption-money': {
      id: '/_authenticated/corruption-money'
      path: '/corruption-money'
      fullPath: '/corruption-money'
      preLoaderRoute: typeof AuthenticatedCorruptionMoneyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/class-feedback': {
      id: '/_authenticated/class-feedback'
      path: '/class-feedback'
      fullPath: '/class-feedback'
      preLoaderRoute: typeof AuthenticatedClassFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/captain-feedback-list': {
      id: '/_authenticated/captain-feedback-list'
      path: '/captain-feedback-list'
      fullPath: '/captain-feedback-list'
      preLoaderRoute: typeof AuthenticatedCaptainFeedbackListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/captain-feedback': {
      id: '/_authenticated/captain-feedback'
      path: '/captain-feedback'
      fullPath: '/captain-feedback'
      preLoaderRoute: typeof AuthenticatedCaptainFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-syllabus': {
      id: '/_authenticated/ai-syllabus'
      path: '/ai-syllabus'
      fullPath: '/ai-syllabus'
      preLoaderRoute: typeof AuthenticatedAiSyllabusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedAiSyllabusRoute: typeof AuthenticatedAiSyllabusRoute
  AuthenticatedCaptainFeedbackRoute: typeof AuthenticatedCaptainFeedbackRoute
  AuthenticatedCaptainFeedbackListRoute: typeof AuthenticatedCaptainFeedbackListRoute
  AuthenticatedClassFeedbackRoute: typeof AuthenticatedClassFeedbackRoute
  AuthenticatedCorruptionMoneyRoute: typeof AuthenticatedCorruptionMoneyRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchoolRulesRoute: typeof AuthenticatedSchoolRulesRoute
  AuthenticatedSeatPlannerRoute: typeof AuthenticatedSeatPlannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedStudentManagementRoute: typeof AuthenticatedStudentManagementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedAiSyllabusRoute: AuthenticatedAiSyllabusRoute,
  AuthenticatedCaptainFeedbackRoute: AuthenticatedCaptainFeedbackRoute,
  AuthenticatedCaptainFeedbackListRoute: AuthenticatedCaptainFeedbackListRoute,
  AuthenticatedClassFeedbackRoute: AuthenticatedClassFeedbackRoute,
  AuthenticatedCorruptionMoneyRoute: AuthenticatedCorruptionMoneyRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchoolRulesRoute: AuthenticatedSchoolRulesRoute,
  AuthenticatedSeatPlannerRoute: AuthenticatedSeatPlannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedStudentManagementRoute: AuthenticatedStudentManagementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
