/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated.sos'
import { Route as AuthenticatedSeatPlannerRouteImport } from './routes/_authenticated.seat-planner'
import { Route as AuthenticatedSchoolRulesRouteImport } from './routes/_authenticated.school-rules'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated.feedback'
import { Route as AuthenticatedClassFeedbackRouteImport } from './routes/_authenticated.class-feedback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeatPlannerRoute =
  AuthenticatedSeatPlannerRouteImport.update({
    id: '/seat-planner',
    path: '/seat-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolRulesRoute =
  AuthenticatedSchoolRulesRouteImport.update({
    id: '/school-rules',
    path: '/school-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassFeedbackRoute =
  AuthenticatedClassFeedbackRouteImport.update({
    id: '/class-feedback',
    path: '/class-feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/sos': typeof AuthenticatedSosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/sos': typeof AuthenticatedSosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/class-feedback': typeof AuthenticatedClassFeedbackRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/school-rules': typeof AuthenticatedSchoolRulesRoute
  '/_authenticated/seat-planner': typeof AuthenticatedSeatPlannerRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/class-feedback'
    | '/feedback'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/school-rules'
    | '/seat-planner'
    | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/class-feedback'
    | '/feedback'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/school-rules'
    | '/seat-planner'
    | '/sos'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/class-feedback'
    | '/_authenticated/feedback'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/school-rules'
    | '/_authenticated/seat-planner'
    | '/_authenticated/sos'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seat-planner': {
      id: '/_authenticated/seat-planner'
      path: '/seat-planner'
      fullPath: '/seat-planner'
      preLoaderRoute: typeof AuthenticatedSeatPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school-rules': {
      id: '/_authenticated/school-rules'
      path: '/school-rules'
      fullPath: '/school-rules'
      preLoaderRoute: typeof AuthenticatedSchoolRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/class-feedback': {
      id: '/_authenticated/class-feedback'
      path: '/class-feedback'
      fullPath: '/class-feedback'
      preLoaderRoute: typeof AuthenticatedClassFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedClassFeedbackRoute: typeof AuthenticatedClassFeedbackRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchoolRulesRoute: typeof AuthenticatedSchoolRulesRoute
  AuthenticatedSeatPlannerRoute: typeof AuthenticatedSeatPlannerRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClassFeedbackRoute: AuthenticatedClassFeedbackRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchoolRulesRoute: AuthenticatedSchoolRulesRoute,
  AuthenticatedSeatPlannerRoute: AuthenticatedSeatPlannerRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
